### ISSUE TITLE
Ignore buttons disappear when filter is changed 

### ISSUE THREAD

**Issue by SteveWooding** [SteveWooding/fc-ignore#1]
If you change any of the filter options at the top of the page, the loans are reloaded. However, when they do reload, the ignore buttons are not re-displayed along with the new loan list.

Loans set to be ignored are also displayed.

### Workaround in the short term
Refresh the page after a change in the filter settings.

**Comment by LoneRifle** [comment]
You need to attach a MutationObserver, like so in FCViz's market.js:
https://github.com/LoneRifle/fcviz/blob/master/js/market.js#L31

Further documentation can be found on MDN:
https://developer.mozilla.org/en/docs/Web/API/MutationObserver

**Comment by SteveWooding** [comment]
Thanks a lot. I'll check that out.
